name: Build succeeds on PR
on:
  pull_request:
    branches:
      - main
jobs:
  Continuous_Integration:
    name: Check if project builds
    runs-on: ubuntu_latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        uses: npm install

      - name: Generate prisma client
        uses: npm run db:generate

      - name: Build the project
        uses: npm run build
