name: Build on PR
on:
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Generate prisma client
        run: npm run db:generate

      - name: Build the project
        run: npm run build
