name: Deploy on Push to dockerhub
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Push to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: pritam12f/venmo-clone:latest

      - name: Verify dockerhub image
        run: docker pull pritam12f/venmo-clone:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull pritam12f/venmo-clone:latest
            sudo docker stop venmo-clone || true
            sudo docker rm venmo-clone || true
            sudo docker run -d --name venmo-clone -p 3005:3000 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e NEXTAUTH_URL=${{secrets.NEXTAUTH_URL}} -e JWT_SECRET=${{secrets.JWT_SECRET}} pritam12f/venmo-clone:latest
